### PR TITLE
Guidelines V1

### PR DESCRIPTION
**Pull request by adriansalazar**
@BrunoBernardino Here is the first version of the Brand Guidelines, I hope you like it!

Ideally, I would like to take an extra day to do QA, revisit the copy and to make it 100% responsive. Let me know if that is possible or if I should go back to the website.

### CODE REVIEW

**Comment by BrunoBernardino** [comment]
Very good. Can you just replace the `apple-touch-icon.png` icon with something more meaningful? Even if it's a very small version of the logo. :)

**Comment by BrunoBernardino** [comment]
You can merge it yourself after that.

**Comment by adriansalazar** [comment]
Hey @BrunoBernardino, I just added the favicons, but I'm not too sure how can I merge my branch with yours. I feel that I maybe don't have write access?

Maybe I'm just being dumb because I haven't done this before, please let me know how to do it :)

**Comment by BrunoBernardino** [comment]
It's good. You just needed to add to your branch and sync, which you did :)

**Comment by BrunoBernardino** [comment]
There you go: http://handbooks.clevertech.biz/guidelines.html

**Comment by adriansalazar** [comment]
Sweet, I think it looks great!

**Pull request merged**
